In [1]:
from keras.datasets import mnist
import numpy as np
from sklearn import tree
import graphviz
from sklearn.metrics import accuracy_score as acc_rate

In [8]:
# download the mnist to the path '~/.keras/datasets/' if it is the first time to be called
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 3s 0us/step


In [21]:
X_train = X_train.reshape(60000,784)
X_test = X_test.reshape(10000,784)

In [22]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [26]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [23]:
# train the model
# initial an decision tree classifier object with given arguments
clf = tree.DecisionTreeClassifier(criterion='entropy',
                                  splitter='best')
# A lot of arguments can be placed into the object
# Refer docs: http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier
clf.fit(X=X_train, y=y_train)

DecisionTreeClassifier(criterion='entropy')

In [31]:
# make prediction
print('\nThe target test data set is:\n', X_test)
print('\nThe predicted result is:\n', clf.predict(X_test))
print('\nAccuracy rate is:\n', acc_rate(y_test, clf.predict(X_test)))


The target test data set is:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

The predicted result is:
 [7 2 1 ... 4 8 6]

Accuracy rate is:
 0.8874


In [30]:
dot_data = tree.export_graphviz(clf,
                                filled=True,
                                rounded=True,
                                impurity=False,
                                special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("mnist", view = True)

'mnist.pdf'