In [1]:
from sklearn.datasets import load_iris
# More toy data sets from sklearn please refer:
# http://scikit-learn.org/stable/datasets/
import numpy as np
import pandas as pd
from sklearn import tree
import graphviz
from sklearn.metrics import accuracy_score as acc_rate

# use this line in terminal if graphviz does not work: conda install python-graphviz 

In [2]:
p2p = pd.read_csv("./p2p.csv")
p2p = p2p.iloc[:,1:-1]
p2p

ratio001  ratio002  ratio003  ratio004  ratio005  ratio006  ratio008  \
0     -0.238174 -0.155186 -0.124784 -0.422984 -0.441998 -0.281685 -0.476657   
1     -0.758472 -0.356497 -0.659060 -0.076745  0.260873 -0.515998 -1.119889   
2     -0.333616 -0.207378  0.508892 -0.263181 -0.496910 -0.276421 -0.372174   
3     -0.444811 -0.478278 -1.056660  0.145204 -0.255298 -0.239247 -0.424368   
4     -0.479096 -0.523014 -1.156061 -0.902393 -0.749504 -0.371168 -0.400809   
5     -1.368040 -0.309276 -0.485109 -0.334205 -0.046633 -0.238589  3.449548   
6     -0.118640 -0.167613 -0.286309 -0.964539 -1.078975 -0.300766 -1.119889   
7     -0.891442 -1.040260 -0.609360 -0.565031 -1.177817 -0.332019 -0.272288   
8     -0.218252 -0.257084 -0.162059 -0.023477  0.271855 -0.250432 -0.138404   
9     -0.355392 -0.291879  1.105293  1.148411  1.787421  4.064475 -1.119889   
10    -0.382264 -0.309276 -1.056660  1.636698 -1.133887 -0.253722 -0.438062   
11    -1.368040 -0.311761 -0.559660 -0.387473 -0.112527 -0.268526  3.449548   
12    -0.334079 -0.035890  0.521317 -0.982295 -0.848346 -0.294186 -0.247675   
13    -0.509211 -0.572720 -0.982110 -0.724834 -0.529857 -0.389262 -0.461238   
14    -0.460100 -0.309276 -1.330011 -1.186487 -1.100940 -0.402421 -1.119889   
15     0.161200 -0.309276 -0.398134 -0.263181  0.041226 -0.008631  0.043555   
16    -0.447127 -0.309276  4.616107 -1.150976 -1.057011 -0.515998  3.449548   
17    -0.796000 -0.500646 -0.634210 -0.174402  0.030243 -0.515998 -0.426666   
18    -0.510137 -0.401233 -0.982110 -0.263181  0.041226 -0.177398 -0.278417   
19    -0.569441 -0.401233 -0.820585 -0.520642 -0.277263 -0.330703 -0.352542   
20     4.180308 -1.040260 -0.472684 -0.360839 -1.122905 -0.269513 -0.333675   
21    -0.345662 -0.309276  0.769818 -1.159854 -1.067993 -0.287936 -1.119889   
22    -0.620869 -0.309276 -0.746035 -0.334205 -0.057616 -0.273789 -0.488053   
23    -0.766812 -0.309276 -0.646635 -0.440740 -0.782452 -0.323137  3.449548   
24    -0.469366 -0.552838 -1.230611 -1.115464 -1.035046 -0.314583 -0.334250   
25    -0.523573 -0.572720 -0.932410 -0.911271 -0.914240 -0.354390 -0.284738   
26    -0.553689 -0.309276 -0.845435 -0.263181 -0.980134 -0.177727 -0.461813   
27    -0.359098 -0.309276  1.291669  0.899829  1.468933  4.064475 -1.119889   
28     0.329381 -0.309276 -0.422984 -0.431862 -0.716557 -0.283659 -0.247101   
29    -0.641254 -0.692016 -0.733610 -1.257511 -1.188799 -0.316228 -0.324960   
...         ...       ...       ...       ...       ...       ...       ...   
15015 -0.450834 -0.363953 -1.056660 -1.142098 -1.046028  4.064475  3.449548   
15016 -0.728820 -0.309276 -0.671485 -1.257511 -1.188799 -0.311951 -0.387688   
15017 -0.328056  0.008845  0.409492 -1.221999 -1.144869 -0.283659 -0.257444   
15018  0.775550 -0.309276 -0.447834  1.308214  0.788026 -0.224442 -0.256486   
15019 -0.360951 -0.281937  1.428344  1.024120  1.633668  0.063744 -0.261753   
15020 -0.448517 -0.361468  4.616107 -1.000051 -0.870310 -0.515998 -0.287228   
15021  0.932612 -0.301820 -0.447834 -0.360839 -0.079580  0.111776  0.164032   
15022 -0.648204 -0.309276 -0.721185 -0.795858 -0.617716 -0.319847 -0.320076   
15023 -1.368040 -0.309276 -0.472684  1.068510  1.688580  4.064475 -0.258018   
15024  4.180308 -0.309276 -0.485109  4.738296 -0.496910 -0.515998 -0.260700   
15025 -0.174701 -0.309276 -0.236609 -0.076745  0.271855 -0.273461 -1.119889   
15026  0.379419  3.977709 -0.422984 -0.644933 -1.210764 -0.307017 -0.249495   
15027  0.075487 -0.309276 -0.373284 -0.458496 -0.914240 -0.293857 -1.119889   
15028  0.839486 -0.142759 -0.447834 -0.680445 -0.694593 -0.308003 -0.287419   
15029 -0.359561 -0.227260  1.316519  0.660125  1.183391 -0.142197 -0.464686   
15030 -0.788587 -0.309276 -0.646635 -0.671567 -0.661646 -0.331361  0.029094   
15031 -0.258560 -0.247143 -0.062659 -0.067867  0.282838  4.064475 -0.248154   
15032 -0.311840 -0.095538  0.223117  1.219435  1.842333 -0.200098 -0.217796   
15033 -0.111690 -0.252114 -0.286309 -0.005721  0.249891 -

In [3]:
print(p2p.columns.values)

['ratio001' 'ratio002' 'ratio003' 'ratio004' 'ratio005' 'ratio006'
 'ratio008' 'ratio011' 'ratio012' 'ratio017' 'ratio018' 'ratio019'
 'ratio027' 'ratio029' 'ratio030' 'DIO' 'DPO' 'DSO' 'turnover' 'status'
 'nace' 'ratio036' 'ratio037' 'ratio039']


In [4]:
# Glance the data set
print(np.delete(p2p.columns.values,19,axis=0)) # name of features
p2p_features = p2p.drop("status",axis=1)
print(p2p.drop("status",axis=1)) # data for the features
p2p_target = p2p["status"]
print("status")  # name of the targets
print(p2p["status"])  # data for the targets

['ratio001' 'ratio002' 'ratio003' 'ratio004' 'ratio005' 'ratio006'
 'ratio008' 'ratio011' 'ratio012' 'ratio017' 'ratio018' 'ratio019'
 'ratio027' 'ratio029' 'ratio030' 'DIO' 'DPO' 'DSO' 'turnover' 'nace'
 'ratio036' 'ratio037' 'ratio039']
       ratio001  ratio002  ratio003  ratio004  ratio005  ratio006  ratio008  \
0     -0.238174 -0.155186 -0.124784 -0.422984 -0.441998 -0.281685 -0.476657   
1     -0.758472 -0.356497 -0.659060 -0.076745  0.260873 -0.515998 -1.119889   
2     -0.333616 -0.207378  0.508892 -0.263181 -0.496910 -0.276421 -0.372174   
3     -0.444811 -0.478278 -1.056660  0.145204 -0.255298 -0.239247 -0.424368   
4     -0.479096 -0.523014 -1.156061 -0.902393 -0.749504 -0.371168 -0.400809   
5     -1.368040 -0.309276 -0.485109 -0.334205 -0.046633 -0.238589  3.449548   
6     -0.118640 -0.167613 -0.286309 -0.964539 -1.078975 -0.300766 -1.119889   
7     -0.891442 -1.040260 -0.609360 -0.565031 -1.177817 -0.332019 -0.272288   
8     -0.218252 -0.257084 -0.162059 -0.023477  0.2

In [5]:
# randomly choose 1/3 of samples as testing data
np.random.seed(123)
test_idx = np.random.randint(0, len(p2p), len(p2p) // 3)
print(test_idx)
print(np.shape(test_idx))


[ 3582 11646  1346 ...  5602 10586 11928]
(5015,)


In [6]:
# training data
train_data = np.delete(np.array(p2p_features), test_idx, axis=0)
train_target = np.delete(np.array(p2p_target), test_idx,axis=0)

In [7]:
# testing data
test_data = np.array(p2p_features)[test_idx]
test_target = np.array(p2p_target)[test_idx]

In [8]:
# train the model
# initial an decision tree classifier object with given arguments
clf = tree.DecisionTreeClassifier(criterion='entropy',
                                  splitter='best')
# A lot of arguments can be placed into the object
# Refer docs: http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier
clf.fit(X=train_data, y=train_target)

DecisionTreeClassifier(criterion='entropy')

In [9]:
# make prediction
print('\nThe target test data set is:\n', test_target)
print('\nThe predicted result is:\n', clf.predict(test_data))
print('\nAccuracy rate is:\n', acc_rate(test_target, clf.predict(test_data)))


The target test data set is:
 [0 0 1 ... 0 0 0]

The predicted result is:
 [0 0 0 ... 0 0 0]

Accuracy rate is:
 0.8699900299102692


In [10]:
# visualizing the tree

dot_data = tree.export_graphviz(clf,
                                out_file=None,
                                feature_names=list(np.delete(p2p.columns.values,19,axis=0)),
                                class_names=list("status"),
                                filled=True,
                                rounded=True,
                                impurity=False,
                                special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("p2p_lending", view = True)


'p2p_lending.pdf'